apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        martinmlouis/activity: true
        martinmlouis/jenkinsnew: true
        martinmlouis/jenkinsx: true
        martinmlouis/node: true
        martinmlouis/pipeline: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        martinmlouis/activity: merge
        martinmlouis/jenkinsnew: merge
        martinmlouis/jenkinsx: merge
        martinmlouis/node: merge
        martinmlouis/pipeline: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - martinmlouis/jenkinsx
        - martinmlouis/activity
        - martinmlouis/jenkinsnew
        - martinmlouis/node
        - martinmlouis/pipeline
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - martinmlouis/jenkinsx
        - martinmlouis/activity
        - martinmlouis/jenkinsnew
        - martinmlouis/node
        - martinmlouis/pipeline
      target_url: http://lighthouse-jx.34.86.122.23.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
